blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.com/channels/994160573333913691/1065131029616136273
    about: Ask questions and discuss with other Sveltepress users in real time.